##############################################################################
##                                 Base Image                               ##
##############################################################################
ARG ROS_DISTRO=melodic
# Ubuntu 18.04.
FROM osrf/ros:${ROS_DISTRO}-desktop-full
ENV TZ=Europe/Berlin
ENV TERM=xterm-256color
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /etc/bash.bashrc

##############################################################################
##                                 Global Dependecies                       ##
##############################################################################
# Install default packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    iputils-ping nano htop git sudo wget curl gedit \
    python-pip \
    python-catkin-tools \
    gdb \
    ros-${ROS_DISTRO}-plotjuggler-ros \
    && rm -rf /var/lib/apt/lists/*

# Install custom dependencies
RUN apt-get update && apt-get install --no-install-recommends -y \
    ros-melodic-cob-default-env-config \
    ros-melodic-cob-voltage-control \
    ros-melodic-cob-frame-tracker \
    ros-melodic-cob-navigation-global \
    ros-melodic-cob-twist-controller \
    ros-melodic-cob-teleop \
    ros-melodic-cob-collision-velocity-filter \
    ros-melodic-cob-control-mode-adapter \
    ros-melodic-cob-image-flip \
    ros-melodic-canopen-motor-node \
    ros-melodic-cob-phidgets \
    ros-melodic-cob-base-controller-utils \
    ros-melodic-cob-base-velocity-smoother \
    ros-melodic-rosserial-python \
    ros-melodic-cob-cam3d-throttle \
    ros-melodic-cob-script-server \
    ros-melodic-cob-obstacle-distance \
    ros-melodic-cob-supported-robots \
    ros-melodic-cob-light \
    ros-melodic-rplidar-ros \
    ros-melodic-rosserial-server \
    ros-melodic-cob-safety-controller \
    ros-melodic-spacenav-node \
    ros-melodic-cob-sick-s300 \
    ros-melodic-cob-linear-nav \
    ros-melodic-cob-hand-bridge \
    ros-melodic-joy \
    ros-melodic-velocity-controllers \
    ros-melodic-cob-gazebo-worlds \
    ros-melodic-cob-sound \
    ros-melodic-rosparam-handler \
    ros-melodic-sick-safetyscanners \
    ros-melodic-cob-phidget-em-state \
    ros-melodic-twist-mux \
    ros-melodic-cob-bms-driver \
    ros-melodic-usb-cam \
    ros-melodic-cob-command-gui \
    ros-melodic-cob-docker-control \
    ros-melodic-cob-mapping-slam \
    ros-melodic-cob-scan-unifier \
    ros-melodic-cob-monitoring \
    ros-melodic-teleop-twist-joy \
    ros-melodic-ati-force-torque \
    ros-melodic-cob-reflector-referencing \
    ros-melodic-costmap-2d \
    ros-melodic-cob-omni-drive-controller \
    ros-melodic-generic-throttle \
    ros-melodic-openni2-launch \
    ros-melodic-joint-state-publisher-gui \
    ros-melodic-openni-launch \
    ros-melodic-cob-mecanum-controller \
    ros-melodic-cob-android-script-server \
    ros-melodic-canopen-chain-node \
    ros-melodic-cob-mimic \
    ros-melodic-cob-sick-lms1xx \
    ros-melodic-cob-helper-tools \
    ros-melodic-joint-trajectory-controller \
    ros-melodic-cob-dashboard \
    ros-melodic-cob-phidget-power-state \
    && rm -rf /var/lib/apt/lists/*

# RUN pip install \
#     <YOUR_PACKAGE>
RUN pip install \
    pyyaml \
    scipy