[TOPICS]
# WrenchStamped (msg.wrench.force/torque)
force_input_raw_x = /base/fts_adaptive_force_controller/debug/force_input_raw|wrench.force.x
force_input_raw_y = /base/fts_adaptive_force_controller/debug/force_input_raw|wrench.force.y
torque_input_raw_z = /base/fts_adaptive_force_controller/debug/force_input_raw|wrench.torque.z

force_input_scaled_limited_x = /base/fts_adaptive_force_controller/debug/force_input_scaled_limited|wrench.force.x
force_input_scaled_limited_y = /base/fts_adaptive_force_controller/debug/force_input_scaled_limited|wrench.force.y
torque_input_scaled_limited_z = /base/fts_adaptive_force_controller/debug/force_input_scaled_limited|wrench.torque.z

output_data_linear_x = /base/output_data|wrench.force.x
output_data_linear_z = /base/output_data|wrench.force.z
output_data_angular_y = /base/output_data|wrench.torque.y
output_data_angular_z = /base/output_data|wrench.torque.z

# TwistStamped (msg.twist.linear/angular)
velocity_output_linear_x = /base/fts_adaptive_force_controller/debug/velocity_output|twist.linear.x
velocity_output_linear_y = /base/fts_adaptive_force_controller/debug/velocity_output|twist.linear.y
velocity_output_angular_z = /base/fts_adaptive_force_controller/debug/velocity_output|twist.angular.z

# Vector3 (msg.x, msg.y, msg.z)
virtual_force_position_x = /base/virtual_forces/modalities_debug/position|x
virtual_force_position_y = /base/virtual_forces/modalities_debug/position|y
virtual_force_resulting_force_x = /base/virtual_forces/modalities_debug/resulting_force|x
virtual_force_resulting_force_y = /base/virtual_forces/modalities_debug/resulting_force|y
virtual_force_resulting_velocity_x = /base/virtual_forces/modalities_debug/resulting_velocity|x
virtual_force_resulting_velocity_y = /base/virtual_forces/modalities_debug/resulting_velocity|y
virtual_force_velocity_in_x = /base/virtual_forces/modalities_debug/velocity_in|x
virtual_force_velocity_in_y = /base/virtual_forces/modalities_debug/velocity_in|y
virtual_force_velocity_out_x = /base/virtual_forces/modalities_debug/velocity_out|x
virtual_force_velocity_out_y = /base/virtual_forces/modalities_debug/velocity_out|y

# Pose2DStamped (msg.pose.x / y / theta)
robot_pose_x = /mobile_robot_pose|pose.x
robot_pose_y = /mobile_robot_pose|pose.y
robot_pose_z = /mobile_robot_pose|pose.theta

# Custom msgs (angenommen Float64 oder Int32 Felder)
path_index_front = /robotrainer_deviation/current_path_index|path_index_front
path_index_left = /robotrainer_deviation/current_path_index|path_index_left
path_index_right = /robotrainer_deviation/current_path_index|path_index_right
robotrainer_deviation_front = /robotrainer_deviation/robotrainer_deviation|front
robotrainer_deviation_left = /robotrainer_deviation/robotrainer_deviation|left
robotrainer_deviation_right = /robotrainer_deviation/robotrainer_deviation|right

# std_msgs / Polar OH1 Sensoren
heart_rate = /biosensors/polar_oh1/hr|data
hrv = /biosensors/polar_oh1/hrv/data|data
ppg_ch0 = /biosensors/polar_oh1/ppg_ch0/data|data
ppg_ch1 = /biosensors/polar_oh1/ppg_ch1/data|data
ppg_ch2 = /biosensors/polar_oh1/ppg_ch2/data|data
ppg_ch3 = /biosensors/polar_oh1/ppg_ch3/data|data
ppi = /biosensors/polar_oh1/ppi|data



#scan_ranges = /base_laser_back/scan/ranges
#scan_intensities = /base_laser_back/scan/intensities
#lower_image_raw = /lower_legs_camera/depth_registered/image_raw
#lower_camera_points_data = /lower_legs_camera/depth_registered/points/data
#upper_image_raw = /upper_body_camera_realsense/color/image_raw
#upper_camera_points = /upper_body_camera_realsense/depth/color/points

#/tf
#/tf_static


